default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-case-conflict
      # - id: no-commit-to-branch
      - id: check-added-large-files

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shellcheck
      - id: shfmt
