name: Test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go: [1.17, 1.18]
        os: [ubuntu-22.04, macos-11, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Lint golangci
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

      - name: Run race detector tests
        if: runner.os != 'Windows'
        run: go test -race ./...

      - name: Run coverage
        if: runner.os == 'Linux'
        run: go test -coverprofile="coverage.out" -covermode=atomic ./...

      - name: Run coverage
        if: runner.os != 'Linux'
        run: go test -coverprofile="coverage.out" ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Upload go report card
        uses: creekorful/goreportcard-action@v1.0
