name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-11, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Run basic tests
        run: go test ./...

      - name: Run race detector tests
        if: runner.os != 'Windows'
        run: go test -race ./...

      - name: Run coverage
        if: runner.os == 'Linux'
        run: go test -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
